services:
  - type: web
    name: agentis
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.1
      - key: OPENAI_API_KEY
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
